# Form implementation generated from reading ui file 'duplicatewizard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1058, 609)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/SheoIcon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.duplicatesListWidget = QtWidgets.QListWidget(parent=Dialog)
        self.duplicatesListWidget.setMinimumSize(QtCore.QSize(151, 0))
        self.duplicatesListWidget.setObjectName("duplicatesListWidget")
        self.verticalLayout_2.addWidget(self.duplicatesListWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.framesListWidget = QtWidgets.QListWidget(parent=Dialog)
        self.framesListWidget.setMinimumSize(QtCore.QSize(151, 0))
        self.framesListWidget.setObjectName("framesListWidget")
        self.verticalLayout_3.addWidget(self.framesListWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.preview = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview.sizePolicy().hasHeightForWidth())
        self.preview.setSizePolicy(sizePolicy)
        self.preview.setText("")
        self.preview.setObjectName("preview")
        self.verticalLayout.addWidget(self.preview)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.replaceButton = QtWidgets.QPushButton(parent=Dialog)
        self.replaceButton.setObjectName("replaceButton")
        self.horizontalLayout.addWidget(self.replaceButton)
        self.autoReplaceButton = QtWidgets.QPushButton(parent=Dialog)
        self.autoReplaceButton.setObjectName("autoReplaceButton")
        self.horizontalLayout.addWidget(self.autoReplaceButton)
        self.finishButton = QtWidgets.QPushButton(parent=Dialog)
        self.finishButton.setObjectName("finishButton")
        self.horizontalLayout.addWidget(self.finishButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.replaceButton.clicked.connect(Dialog.select_main_copy) # type: ignore
        self.finishButton.clicked.connect(Dialog.accept) # type: ignore
        self.framesListWidget.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog.update_preview) # type: ignore
        self.duplicatesListWidget.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog.update_frames) # type: ignore
        self.autoReplaceButton.clicked.connect(Dialog.autoreplace_all) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Duplicate Sprite Manager"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Duplicate Groups</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Frames</span></p></body></html>"))
        self.replaceButton.setText(_translate("Dialog", "Select Main Copy"))
        self.autoReplaceButton.setText(_translate("Dialog", "Autoreplace All"))
        self.finishButton.setText(_translate("Dialog", "Finish"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
